name: hifdh
description: "A Quran memorization tracking app."
publish_to: 'none'
version: 2.0.0+200

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/quran.db

  fonts:
    - family: QuranFont
      fonts:
        - asset: assets/quran.ttf
    - family: SurahFont
      fonts:
        - asset: assets/surah.ttf
